_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x/138205316/model_final_a3ec72.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 5
DATASETS:
  TRAIN: ("dla_train",)
  TEST: ("dla_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 75500
  IMS_PER_BATCH: 2
  BASE_LR: 0.0009
DATALOADER:
  NUM_WORKERS: 1