_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
DATASETS:
  TRAIN: ("publaynet_train",)
  TEST: ("publaynet_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 75500
  IMS_PER_BATCH: 2
  BASE_LR: 0.0009
DATALOADER:
  NUM_WORKERS: 1
